//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvertisementPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdsSet
    {
        public int Id { get; set; }
        public int Id_Organisation { get; set; }
        public int Id_Newspaper { get; set; }
        public string Number { get; set; }
        public string Size { get; set; }
    
        public virtual NewspapersSet NewspapersSet { get; set; }
        public virtual OrganisationsSet OrganisationsSet { get; set; }
    }
}
