//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvertisementPro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDAdEntities : DbContext
    {
        public BDAdEntities()
            : base("name=BDAdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdsSet> AdsSet { get; set; }
        public virtual DbSet<NewspapersSet> NewspapersSet { get; set; }
        public virtual DbSet<OrganisationsSet> OrganisationsSet { get; set; }
    }
}
